# Generated by Django 2.2.1 on 2019-05-21 12:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{10}', 'Phone number format needs to be #########')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='New', max_length=10),
        ),
    ]
