# Generated by Django 2.2.1 on 2019-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanage', '0002_auto_20190521_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(auto_now_add=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Start Date'),
        ),
    ]
