# Generated by Django 2.2.1 on 2019-05-21 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanage', '0003_auto_20190521_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
