# Generated by Django 2.2.1 on 2019-05-23 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanage', '0004_auto_20190521_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_number',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{2}[0-9]{4}', 'Employee number format needs to be AA0000')], verbose_name='Employee Number'),
        ),
    ]
